apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-node
  strategy:
    canary:
      canaryService: sample-node-preview
      steps:
      - setWeight: 25
      - analysis:
          args:
          - name: url
            value: http://sample-node-preview:3000/success/98
          templateName: http-benchmark
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
        version: v0.4.52
    spec:
      containers:
      - env:
        - name: CONFIGMAP_HASH
          value: 59ea55a099664e452e9d68207f7d6b42
        - name: SECRET_HASH
          value: ''
        envFrom:
        - configMapRef:
            name: sample-node
        image: nalbam/sample-node:v0.4.52
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sample-node
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 110m
            memory: 134Mi
          requests:
            cpu: 100m
            memory: 120Mi
